#:schema node_modules/wrangler/config-schema.json
name = "snappass"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "SNAPPASS", id = "2ad09ca3ce784b418817d8c51a6fc383" },
]

rules = [
  { type = "Text", globs = ["**/*.css"], fallthrough = true }
]